### ISSUE TITLE
"Could not find the requested value 'NormalStash'" using .NET Framework 4.7.2

### ISSUE THREAD

**Issue by Zolomon** [Celisuis/ExileNET#1]
Hi!

I'm trying to use ExileNET to write my own item indexer. 

When I run this code: 
```
private async void DoStuff()
{
    Client client = new Client();
    await client.VerifyConnectionAsync();
    var publicStash = await client.Api.GetPublicStashesAsync();
    Console.WriteLine(publicStash);
}
```
I get the error
```
System.ArgumentException
  HResult=0x80070057
  Message=Could not find the requested value NormalStash.
  Source=mscorlib
  StackTrace:
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at System.Enum.Parse(Type enumType, String value)
   at ExileNET.API.PublicStashTabs.StashTab..ctor(JObject rawData) in C:\Coding\ExileNET\ExileNET\API\Public Stash Tabs\StashTab.cs:line 23
   at ExileNET.API.PublicStashTabs.Stash..ctor(JObject rawData) in C:\Coding\ExileNET\ExileNET\API\Public Stash Tabs\Stash.cs:line 17
   at ExileNET.API.ExileAPI.<GetPublicStashesAsync>d__3.MoveNext() in C:\Coding\ExileNET\ExileNET\API\ExileAPI.cs:line 37
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Poem.MainWindow.<DoStuff>d__2.MoveNext() in C:\Users\zol\code\c#\poem\Poem\Poem\MainWindow.xaml.cs:line 38
```

**Comment by Zolomon** [comment]
So it appears to be [this line ](https://github.com/Celisuis/ExileNET/blob/master/API/Public%20Stash%20Tabs/StashTab.cs#L23) that causes the problem. 

I assume that the `StashType` enum needs to be annotated with string values so that they can be parsed 1:1; for example "NormalStash", "PremiumStash" etc. as according to [the wiki](https://pathofexile.gamepedia.com/Public_stash_tab_API)

**Comment by Celisuis** [comment]
That does appear to be the case. I'll have a fix up for it later on today, but renaming the enums will work on your side for now aswell. I also have to add some new values that I've just found aswell. i shall let you know when the update is live :)

**Comment by Celisuis** [comment]
Should be fixed in latest release. Nuget just needs to approve the file. Otherwise you can recompile from source.
